from enum import Enum


class SegmentType(Enum):
    DEFAULT = "DEFAULT"
    BUILD_FAILURE = "BUILD_FAILURE"
    OOM = "OOM"
    MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
    TEST_FAILURE = "TEST_FAILURE"
    INFRA_FAILURE = "INFRA_FAILURE"
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
